---

- name: Remove ZTP GitOps resources
  ansible.builtin.include_role:
    name: redhatci.ocp.remove_ztp_gitops_resources
  vars:
    rzgr_policies_namespace: "{{ spoke_cluster_name }}-policies"

- name: Detach spoke cluster from hub cluster
  ansible.builtin.include_role:
    name: redhatci.ocp.acm_detach_spoke_cluster
  vars:
    adsc_cluster_name: "{{ spoke_cluster_name }}"

...
