#!/usr/bin/env python3
#
# Copyright (C) 2022 Red Hat, Inc. 
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

'''Take the output of 2 commands `oc get -o json apirequestcounts`
before and after a workload run and display which API will be removed
in the future.
'''

import sys
import json


def k8s2ocp(kver):
    return str(float(kver) + 2.87)


def compute_removed_apis(before, after, output):
    before_dict = {}
    for item in before["items"]:
        if "removedInRelease" in item["status"]:
            before_dict[item['metadata']['name']] = item
    after_dict = {}
    for item in after["items"]:
        if "removedInRelease" in item["status"]:
            after_dict[item['metadata']['name']] = item
    for api_name in after_dict:
        item = after_dict[api_name]
        if (api_name not in before_dict or
            after_dict[api_name]["status"]["requestCount"] > before_dict[api_name]["status"]["requestCount"]):
            print(f"{item['metadata']['name']} will be removed "
                  f"in OCP {k8s2ocp(item['status']['removedInRelease'])}",
                  file=output)


def main(args):
    if len(args) != 4:
        print(f"Usage: {argv[0]} <apirequestcounts.before.json> <apirequestcounts.after.json> <output filename>",
              file=sys.stderr)
        return 1
    with open(sys.argv[1]) as before_stream:
        before = json.load(before_stream)
    with open(sys.argv[2]) as after_stream:
        after = json.load(after_stream)
    with open(sys.argv[3], "w") as output:
        compute_removed_apis(before, after, output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))

# compute_removed_apis ends here
