---
- name: Set default variables if none provided
  ansible.biultin.set_fact:
    openshift_app_ns: "{{ dci_openshift_app_ns | default('myns') }}"
    openshift_app_image: "{{ dci_openshift_app_image | default('quay.io/tonyskapunk/psf-httpbin:latest') }}"
    openshift_app_registry: "{{ dci_local_registry }}"

- name: Mirror image in disconnected environment
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_images
  vars:
    images:
      - "{{ openshift_app_image }}"
    authfile: "{{ pullsecret_tmp_file }}"
  when:
    - dci_disconnected | default(false) | bool
    - openshift_app_registry | length
