---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Distribution
  debug: msg="{{ ansible_distribution }}"

- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"

- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"

- name: Get uptime information
  ansible.builtin.shell: /usr/bin/uptime
  register: result

- name: Debug 
  debug: 
    msg: result.stdout

- name: "Install required rpm packages"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3-openshift
    - python3-pyyaml
  become: true

- name: "Set default variables if none provided"
  set_fact:
    openshift_app_ns: "{{ dci_openshift_app_ns | default('myns') }}"
    openshift_app_image: "{{ dci_openshift_app_image | default('mirror.gcr.io/kennethreitz/httpbin:latest') }}"
    openshift_app_registry: "{{ dci_local_registry }}"
    openshift_app_cmds: "{{ dci_openshift_app_cmd | default(['gunicorn', '-b', '[::]:8080', 'httpbin:app', '-k', 'gevent']) }}"

- name: "Mirror pod image (disconnected)"
  include_role:
    name: redhatci.ocp.mirror_images
  vars:
    mi_images:
      - "{{ openshift_app_image }}"
    mi_authfile: "{{ pullsecret_tmp_file }}"
    mi_registry: "{{ openshift_app_registry }}"
  when:
    - dci_disconnected | default(false) | bool
    - openshift_app_registry | length
